### PR TITLE
fix(mods/rpg_system,i18n): make mod translatable

### LINKED ISSUE #7422: RPG System mod Lua strings are not available for translation
### Describe the bug

```
  gapi.add_msg(
    MsgType.mixed,
    color_info("[System]")
      .. " initialized. Welcome "
      .. color_highlight("[User]")
      .. " of world IB-73758-R. Use your "
      .. color_info("[System Interface]")
      .. " to access the "
      .. color_info("[System]")
      .. "."
  )
```
This approach to msg does not provide meanings for string extraction and subsequent translations, making mod unable to be localized in full.

### Steps To Reproduce

1. Go to Transifex
2. Filter to `occurrence:data/mods/rpg_system/ text:welcome`
3. No results

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26200.6899 (25H2)
- Game Version: d770374 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    RPG System [rpg_system]
]

### Additional context

This should be the valid approach: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/docs/en/mod/lua/tutorial/modding.md#translation-functions

And something like this as a possible solution in this specific case:
```

  local gettext = locale.gettext
  local msg = gettext("%s initialized. Welcome %s of world IB-73758-R. Use your %s to access the %s.")
	gapi.add_msg(
	  MsgType.mixed,
	  string.format(
		msg,
		color_info(gettext("[RPG System]")),
		color_highlight(gettext("[User]")),
		color_info(gettext("[System Interface]")),
		color_info(gettext("[System]"))
	  )
	)
```

Probably, other Lua mods are affected as well. Perhaps some form of automated in-repo text function check for Lua mods could be implemented for future validations.

### PR DESCRIPTION
**Pull request by scarf005**
closes #7422 

`lang/extract_json_strings.py --project "cataclysm-bn" --input data/mods/rpg_system -o rpg.pot`
```
#: data/mods/rpg_system/main.lua
#, c-format
msgid "You now have %s trait slots."
msgstr ""

#: data/mods/rpg_system/main.lua
msgid "New trait slot unlocked!"
msgid_plural "New trait slots unlocked!"
msgstr[0] ""
msgstr[1] ""
```

### CODE REVIEW

File: data/mods/rpg_system/main.lua [hunk 1]
```diff
@@ -321,13 +318,18 @@ mod.on_monster_killed = function(params)
       gapi.add_msg(
         MsgType.good,
         color_good(
-          string.format("✦ %d stat point%s earned!", stat_points_earned, stat_points_earned > 1 and "s" or "")
+          string.format(
+            gettext("✦ %d stat point%s earned!"),
```
Comment (olanti-p) [inline data/mods/rpg_system/main.lua]: Adding `s` is an English thing, in other languages it'll be gibberish.
For plural forms exists `ngettext`.
(or `vgettext`? forgot how it's called in Lua)

Comment (scarf005) [reply data/mods/rpg_system/main.lua]: so it was `vgettext` (dunno why it's not `ngettext` like GNU gettext?) 
applied and force-pushed in [`7694be0` (#7580)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7580/commits/7694be0e2965fe16467e45be6c375fe2439b738f)

Comment (olanti-p) [reply data/mods/rpg_system/main.lua]: > why it's not ngettext like GNU gettext?

C++ code uses `vgettext` because on some systems, `libintl` is included with standard library, so `ngettext` function provided by stdlib would conflict with `ngettext` function used by the game (which is a custom implementation, and it must be custom in order for mod localizations to work). Lua just reuses C++ name to avoid confusion.
