### PR TITLE
fix: fix switching tileset not working due to vehicle fallback

### LINKED ISSUE #7999: Unable to switch between tilesets on Windows build of 2026-01-28.
### Describe the bug

When attempting to switch between tilesets while in-world, it fails, saying "invalid string position." 

This has been confirmed to persist even after reinstalling the game. Tested with a clean world and a random character to rule out issues with save files. Persists.

Image

### Steps To Reproduce

1. Make a random world and a random character.
2. Start a game with both.
3. Go into options and attempt to switch between tilesets. For my issue it was switching from UndeadPeople[New!] to Ultica.

### Screenshots

Image

### Versions and configuration

Windows 10, Tiles, V2

2026-01-28 experimental build

### Additional context

I have only encountered this problem in this release version. Last version used before this was the Cloning release [I think 2026-01-16?]. Before that it was the 2025-12-30 release.

### PR DESCRIPTION
**Pull request by AzmodiusX**
## Purpose of change (The Why)

May resolve #7999

## Describe the solution (The How)

Use tile categories for the fallback so it doesn't try going through the vehicle tile case.
Honestly not sure why it worked at all.

## Describe alternatives you've considered

Removing the fallback

## Testing

Spawn, make a vehicle, then try to change tileset.
Errors before, doesn't now.

### CODE REVIEW

File: src/cata_tiles.cpp [hunk 1]
```diff
@@ -2696,9 +2696,12 @@ auto cata_tiles::find_tile_looks_like( const std::string &id, TILE_CATEGORY cate
...
             // vehicle parts start with vp_ for their tiles, but not their IDs
-            const vpart_id base_vpid( id.substr( 3 ) );
-            if( !base_vpid.is_valid() ) {
-                return find_tile_looks_like( id.substr( 3 ), category, looks_like_jumps_limit - 1 );
+            auto base_id = id.substr( 3 );
+            const vpart_id base_vpid( base_id );
+            if( !base_vpid.is_valid() ) {  // Fixed Fallback
+                auto ret = find_tile_looks_like( base_id, C_FURNITURE, looks_like_jumps_limit - 1 );
+                if( !ret.has_value() ) { ret = find_tile_looks_like( base_id, C_TERRAIN, looks_like_jumps_limit - 1 ); }
+                return ret;
```
Comment (scarf005) [inline src/cata_tiles.cpp]:
```suggestion
                find_tile_looks_like( base_id, C_FURNITURE, looks_like_jumps_limit - 1 )
                    .or_else( [&, this]{ return find_tile_looks_like( base_id, C_TERRAIN, looks_like_jumps_limit - 1 ); } );
```
https://en.cppreference.com/w/cpp/utility/optional/or_else.html
monads go brrrrrrrrrrrrrrrrrr

Comment (AzmodiusX) [reply src/cata_tiles.cpp]: New tech just dropped
