### PR TITLE
fix(i18n): use untranslated mod names in game report

### LINKED ISSUE #6932: game report should not translate mod names
> Mods loaded: [
> 밝은 밤 [bn],
> NPC 욕구 제거 [no_npc_food],
> 영양수치 단순화 [novitamins],
> 철도역 금지 [No_Rail_Stations],
> 좀비 부활 방지 [no_reviving_zombies],
> 진균 성장 제한 [limit_fungal_growth],
> UDP 리덕스 [udp_redux],
> 밝은밤용 자긍심 깃발 [pride_flags],
> 태블릿 e북 [tablet_ebook]
> ]

while mod id isn't translated, it does make harder for others to read.

refer to https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6928

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change (The Why)

resolves #6932

## Testing

image

1. set language other than english
2. export game report
3. mod names are in english

```
- OS: Linux
    - OS Version: <unknown>
- Game Version: HEAD-HASH (2026-01-10) [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language: 한국어 [ko_KR]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    UDP Redux [udp_redux],
    Pride Flags for BN [pride_flags],
    Tablet e-book [tablet_ebook]
]
```

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

File: src/game_info.cpp [hunk 1]
```diff
@@ -407,7 +406,7 @@ auto game_info::mods_loaded() -> std::string
     std::transform( mod_ids.begin(), mod_ids.end(),
     std::back_inserter( mod_names ), []( const mod_id mod ) -> std::string {
         // e.g. "Dark Days Ahead [dda]".
-        return string_format( "%s [%s]", remove_color_tags( mod->name() ), mod->ident.str() );
```
Comment (WishDuck) [inline src/game_info.cpp:410]: Can we keep remove_color_tags so it doesn't get to the
<color_red>P</color><color_pink>r</color><color_yellow>i</color><color_green>d</color><color_blue>e</color> <color_magenta>F</color><color_red>l</color><color_pink>a</color><color_yellow>g</color><color_green>s</color> <color_blue>f</color><color_magenta>o</color><color_red>r</color> <color_pink>B</color><color_yellow>N</color>
In mod list

Comment (scarf005) [reply src/game_info.cpp:410]: fixed and force-pushed

File: src/game_info.cpp [hunk 2]
```diff
@@ -402,13 +403,10 @@ auto game_info::mods_loaded() -> std::string
...
 
-    std::vector<std::string> mod_names;
-    mod_names.reserve( mod_ids.size() );
-    std::transform( mod_ids.begin(), mod_ids.end(),
-    std::back_inserter( mod_names ), []( const mod_id mod ) -> std::string {
-        // e.g. "Dark Days Ahead [dda]".
-        return string_format( "%s [%s]", remove_color_tags( mod->name() ), mod->ident.str() );
-    } );
+    // e.g. "Bright Nights [bn]".
+    const auto mod_names =
```
Comment (WishDuck) [inline src/game_info.cpp:408]: ?

Comment (scarf005) [reply src/game_info.cpp:408]: > ?

??

**Review by WishDuck — APPROVED** [review]
I meant green checkymark
