### PR TITLE
fix(UI): scaling factor for high-dpi displays

### LINKED ISSUE #7437: Improper scaling factor on high-dpi and Apple Retina displays
### Describe the bug

When adjusting the scaling factor to `2x` or `4x`, the game's math fails to account for the difference between logical and physical pixels. This means that high-dpi and Apple Retina displays are forced to use much smaller text and sprite sizes than are necessary.

My PR fixes this discrepancy here
- #7427 

### Steps To Reproduce

1. Change scaling factor to 2x or 4x on a high-dpi display
2. Reload
3. Despite in most cases fitting, the config change fails and reverts to 1x

### Screenshots

_No response_

### Versions and configuration

All depends on hardware, every version of BN

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rachel-bousfield**
#### Summary
This PR fixes the scaling factor for high-dpi displays. 

#### Purpose of change

The number of pixels returned by `SDL_GetWindowSize` do not take into account dpi scaling, like on Apple Retina displays. Thankfully SDL2 provides a `SDL_GetWindowSizeInPixels` for accounting for exactly this.

Additionally, even in full screen mode the dimensions of `SDL_DisplayMode` are incorrect due to `SDL_GetDesktopDisplayMode` similarly not factoring in dpi scale.

#### Describe the solution

Switch to `SDL_GetWindowSizeInPixels` and implement a new `get_display_scale` function for measuring the dpi scaling ratios. The measurement creates a small, hidden window to quickly measure the horizontal and vertical stretch necessary to account for dpi. On failure the return values are 1x, ensuring no logical change.

#### Describe alternatives you've considered

One could perhaps imagine a larger refactor where we always perform window measurements, but even in this case we'd want precisely the same affordance provided by `get_display_scale`. This keeps things minimal and known to not break other platforms.

#### Testing

| before | after |
| - | - |
| image | image |

I've tested this on my MacBook in each mode, though given it's backend agnostic it should work cross-platform. A friend has also on Windows and I'll soon be on Linux with an intentionally out-dated SDL version too.

 **EDIT**: Confirmed it works on Linux with and without old versions of SDL (pre 2022)
 
 Resolves #7437

### CODE REVIEW

File: src/sdltiles.cpp [hunk 1]
```diff
@@ -3463,6 +3463,37 @@ int projected_window_height()
     return get_option<int>( "TERMINAL_Y" ) * fontheight;
 }
 
+// Measures scaling factor for high-dpi displays
+static std::pair<float, float> get_display_scale( int display_index )
```
Comment (WishDuck) [inline src/sdltiles.cpp:3467]: Any reason why this is defined? Completely unused by this PR.

Comment (rachel-bousfield) [reply src/sdltiles.cpp:3467]: Apologies, accidentally left out the last 3 lines of my diff. It should make much more sense now :)

**Comment by rachel-bousfield** [comment]
@scarf005 Here's what the game looks like at `1x` on my MacBook.

Screenshot 2025-11-09 at 9 40 40 AM

For many players this is acceptable, but some need things a bit bigger. For them the game provides a `scaling_factor` which they can change in the settings to `2x` like so:

Screenshot 2025-11-09 at 9 41 30 AM

Observe that the logically works. The pixels don't run off the ends, tiles during gameplay look great. It's exactly as it's supposed to be.

And yet, on `main` the game would look like the first image. That's because when seeing if the tiles would fit, the game incorrectly thinks my screen is half as wide and tall as it actually is.  That's because `SDL_GetWindowSize` doesn't take into account the fact that I have a DPI scale of `2x` at play with my Apple Retina display.

**Comment by KheirFerrum** [comment]
On the downside I can't replicate the issue and the solution on Windows 11, no matter what I set my resolution scaling to (from 100% to 225%), how I overwrite the resolution scaling behaviour (by application, system, or system (enhanced)) or even the renderer itself (software, direct3d or opengl), I am unable to cause the game to fail to render a resolution scale that it should be able to scale to.

On the upside I have noticed no difference in rendering behaviour between the two builds from my testing. This issue seems to be a niche issue affecting either specific OS or very specific hardware configurations. Have contacted other developers on the team to see if I can get anyone to replicate the issue and solution. With any luck we'll be able to nip this one.

**Review by RoyalFox2140 — APPROVED** [review]
