### PR TITLE
fix: Plutonium batteries now charge when outside the reality bubble, plutonium batteries now recharge while stashed

### LINKED ISSUE #8119: Plutonium battery not recharging while stashed
### Describe the bug

A plutonium battery stowed inside a belt/scabbard/webbing stops recharging

### Steps To Reproduce

Insert a light plutonium battery(0/1000) into an electrified rapier(off)
Store electrified rapier in survivor belt
Wait for multiple hours
The battery charge doesn't change

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.6466 (22H2)
- Game Version: e6f933f (2026-02-11) [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Closable tear in reality [nuclear_tear],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    UDP Redux [udp_redux],
    Tablet e-book [tablet_ebook],
    Change Hairstyle [change_hairstyle],
    Bionic Slots [cbm_slots],
    Magical Nights [MagicalNights],
    RPG System [rpg_system],
    Lethal Zombies [lethal_zeds],
    Civilians [civilians],
    3x Healing [3x_healing],
    No Lifting Reqs [disable_lifting]
]

### Additional context

_No response_

### LINKED ISSUE #8298: Plutonium batteries don't recharge outside of the reality bubble
### Describe the bug

If you take any plutonium battery and put it on the ground, it will recharge at 1% per hour. To do this, you need to be near it. If you go far enough away and leave the reality bubble, the battery will stop recharging.

So for the recharging mechanism to work, batteries always need to be carried in your pocket. They recharge during sleep, but they need to be nearby. If they're far away, there will be no recharging.

I expect that recharging should always work. If I go far away and come back, the charge in the battery should reflect the time that has passed since I left.

### Steps To Reproduce

1. Put the battery on the ground.
2. Go far enough to leave the reality bubble.
3. Wait a few hours.
4. Come back.
5. The battery charge won't have changed.

### Screenshots

_No response_

### Versions and configuration

Game version: 0.10.0 Stable

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by boniondev**
## Purpose of change (The Why)

fixes #8298
fixes #8119 (By sheer coincidence!)

## Describe the solution (The How)

Taking a look around the code, it appears there is no kind of mechanism to take into account the time since an item it was last processed, apart for food rotting. This is why time-based charging relics don't charge out of the bubble, they are effectively frozen. This PR adds a `last_relic_process` variable to the item via `set_var`.

Ideally, the `last_relic_process` is set to the current time everytime `relic_process` is called. When the item is out of the bubble, the `last_relic_process` stops getting updated. When the item is back in the bubble, `last_relic_process` will be a certain amount of time, which is taken into account during `relic_process`, charging the relic appropriately.

The initial value is set to ~~calendar::turn_zero, like the rot timer~~ 0.0(implicitly casted to `int`, so equivalent to `calendar::turn_zero`). Just like you'd find rotten fresh food after a year, you'd find a plutonium battery to be fully charged after a year.

## Describe alternatives you've considered

Ideally you'd want a single, universal timer to be used for all the "catch-up" needs, but I do not feel confident as of right now to perform such a refactor. Perhaps it will be one of my future PRs?

## Testing

Keep in mind, plutonium batteries recharge 1% every 12 minutes. In the case of the light plutonium battery, it's 4 charges every 12 minutes.
For #8119:
Spawn electrified rapier, put empty light plutonium battery inside it. Put it inside worn survival belt. Wait 36 minutes. Expected charges are (36/12)*4=12.
Take out electrified rapier. Still at 0. Wait another 12 minutes. Charges are now at 16. Catch-up **does** work, albeit with a small caveat. See additional context.`*`

For #8298:
Activate electrified rapier to discharge the battery completely. Take out battery that is now completely drained, and drop it. Location is 0,-96,-70. Teleport to 0,-65,-70. Wait for 120 minutes. Expected charges are (120/12)*4=40. Teleport back to 0,-96,-70. Charges are still 0. Wait another 12 minutes. Charges are now... 1000/1000? Perhaps it's the teleport? 

Discharge battery again. Teleport to 0,-65,70 again. Note the time. 6:20:31 PM. Walk back to 0,-96,-70. Time is now 6:34:50PM. Expected charges are 40. Battery is still at 0. Wait 12 minutes. Battery is at now 1000/1000. Turn to ash right at my desk.`**`

Both tests now work as of commit [d571c1e](https://github.com/cataclysmbn/Cataclysm-BN/pull/8342/commits/d571c1ec8ad3eca5f94d62ce28d3ec6bbe33e4b6)!

## Additional context

`*`Catch-up works correctly when inside items that are stashed away, but since the process_relic is only triggered every interval, the charge is not updated when the item is taken out, but on the next interval. I am not sure if fixing this is in the scope of this PR, but it's most likely something I'll get onto eventually. For now I'll settle for what I got.

`**`The likely reason for this is that the `last_relic_check` is not saved to disk when unloading the item, and is instead set to the default value when loaded, which is `calendar::turn`. Fixing this should be as easy as adding the field in whatever list of properties is saved when the item is unloaded.

## Checklist

I'm following more or less what last_rot_check does for this (except being used for rot checking, obviously)
- [x] Add the variable in a suitable place, and wherever it is needed
- [x] Actually use it during relic processing, take it into account during time-based relic charging
- [x] Does it _actually_ work? Yes!
- [x] Fix the fully charging bug (Fixed as of [c1ca81d](https://github.com/cataclysmbn/Cataclysm-BN/pull/8342/commits/c1ca81db589f9fb9b1fe1178a3e6f4ab11179ba6))

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Addendum

This is my absolute first PR and occasion on working on any Cataclysm codebase, or big C++ codebase in general. It's very likely that I will get things wrong, forget to add things where they are needed, and so on. If something is usually done in a way that I did not follow, please do tell, as I assume there is a certain "good way" to contribute to the code.

### CODE REVIEW

**Comment by SYPIAC** [comment]
Would this also worked for stashed batteries? https://github.com/cataclysmbn/Cataclysm-BN/issues/8119

**Comment by boniondev** [comment]
> Would this also worked for stashed batteries? #8119

I believe it should, since if it doesn't charge, it also means the process_relic is not getting called, and thus, the last_relic process stays in the past. I will test that out too.

**Comment by boniondev** [comment]
This PR will indeed fix #8119. Description updated, tests done, needs some more tweaks due to value not being saved.

File: src/item.h [hunk 1]
```diff
@@ -1007,6 +1007,12 @@ class item : public location_visitable<item>, public game_object<item>
             rot += val;
         }
 
+        /** Get the last time this relic was checked */
+        time_point get_last_relic_process() const;
+
+        /** Update the time this relic was checked with the current turn */
+        void update_last_relic_process();
+
```
Comment (scarf005) [inline src/item.h]:
```suggestion
```

can we inline these functions directly into `relics.cpp`? 
- it's not used anywhere else outside `relics.cpp`
- `get_var` and `set_var` is public method so it can be cleanly inlined
- modifying `item.h` causes tons of rebuilds
thus there seems to be little benefit to making it a separate method.

**Comment by chaosvolt** [comment]
Okay new problem: it does trigger after waiting long enough, but something else is screwed up. I waited 6 hours and it filled this battery up entirely, it should've only filled it by 30 charges or 6%:
image

**Comment by boniondev** [comment]
Removed the extra fluff in item.cpp and item.h, now it's all directly inside relic.cpp
As for the magical full charging, I'll have to look into it, but I suspect it's something related to the default value being 0.0, which I assume gets interpreted as turn zero (Why would the value be missing and the default be used instead though?)

**Comment by boniondev** [comment]
@chaosvolt I can't seem to reproduce the scrungle you're having
I tried waiting 6 hours with the battery on the character, works fine
I tried waiting 6 hours with the battery on the ground next to the character, works fine
I tried waiting 6 hours with the battery on the ground outside the reality bubble, still works fine
The thing where it only updates on the next cycle is still a thing, but I don't think it's something I can fix easily in this PR.
Can you give me the steps you did to encounter the magical full charging bug?

**Comment by chaosvolt** [comment]
> Can you give me the steps you did to encounter the magical full charging bug?

1. Compiled and load-tested.
2. Spawned in a tazer and a plutonium battery.
3. Loaded the battery in the tazer, zapped a monster with it to deplete charges.
4. Unloaded it from the tazer.
5. Waited 6 hours, it was fully charged when it should've been at 30/500.

**Comment by boniondev** [comment]
@chaosvolt 
After some debugging, I know what's scrungling it
When the cell is spawned for the first time, `last_relic_process` is not set, so it defaults to `turn_zero`. Ideally, since we simulate the cell "existing since day 1", it works correctly. Under normal gameplay, the player would just find the cell fully charged, because at least one cycle would pass between the cell spawning and the player finding it.
So in a way, testing it by spawning it **is** what causes the bug. After the fully charging first cycle, the cell charges normally, in and out of the bubble. 
If you think a player might be able to find the cell within 12 minutes (the current interval) of it spawning for the first time, I can add in a check that checks if the player has it in their inventory, which will make it _not_ "magically recharge", though I feel like this'd be a fringe case. Let me know.

Also I fixed a possible bug where it would charge by `rate * rate * multiplier` instead of `rate * multiplier`

**Comment by boniondev** [comment]
TODO as requested by chaosvolt:
Professions that start with plutonium batteries shouldn't start with fully charged batteries. Add check before using turn zero to see if it's in a player's inventory, use current turn if it is

**Comment by boniondev** [comment]
All is done. One possible exploit though.
Since I cannot retroactively tell if the plutonium battery **was** in a player's inventory, professions starting with plutonium batteries can opt to drop it on the ground _before_ the first charge cycle to make it fully charge. This is not fixable easily without having to possibly touch item.cpp.
