### PR TITLE
fix(mods/rpg_system): make RPG System mod strings translatable

### LINKED ISSUE #7606: RPG System mod Lua strings are not available for translation, part 2
> @scarf005 
> 
> Some of them strings are still missing as of https://github.com/cataclysmbnteam/Cataclysm-BN/commit/808e7adfafd13ffe89a5e3b754ec45c19ade6cb1
> 
> 1. Entirety of `help_text section`, starting from line 1060
> 2. `local stat_points = get_char_value` is not calling localized stats names
> 3. `skill_data.name` in `local displayed_skills` is not calling localized skills names
> 4. `gdebug.log_info` messages, although those are not that important
> 
> A little inconvenience: `string.format(gettext("Your soul is %s for 3 days."), color_bad(gettext("damaged")))`
> This "damaged" is already established in BN language data and can be awkward to construct a proper translation around it. Not sure if text coloring is worth it in this case. 

 _Originally posted by @vorpal-void in [#7422](https://github.com/cataclysmbnteam/Cataclysm-BN/issues/7422#issuecomment-3634531178)_

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change (The Why)

closes #7606

## Describe the solution (The How)

Wrap untranslated strings in `gettext()`:
- Stat labels (STR:, DEX:, INT:, PER:)
- Skill names in the display
- Help text section strings

## Describe alternatives you've considered

N/A

## Testing

Visual inspection of the code.

## Additional context

N/A

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

File: data/mods/rpg_system/main.lua [hunk 1]
```diff
@@ -1057,37 +1057,46 @@ mod.show_about_screen = function(player)
...
 
-  help_text = help_text .. "Welcome to the " .. color_info("[System]") .. "! You, among\n"
-  help_text = help_text .. "all inhabitants of world IB-73758-R, have\n"
-  help_text = help_text .. "been blessed with a chance at greatness\n"
-  help_text = help_text .. "for your great deeds doing " .. color_warning("[REASON NOT FOUND]") .. ".\n"
-  help_text = help_text .. "Admire below the power made available:\n\n"
+  help_text = help_text
+    .. string.format(
+      gettext(
+        "Welcome to the %s! You, among all inhabitants of world IB-73758-R, have been blessed with a chance at greatness for your great deeds doing %s."
```
Comment (WishDuck) [inline data/mods/rpg_system/main.lua:1071]: Unsure what to do here; Looks better with newlines (in english at least), but guessing translation prefers it be one sentence. Everything else looks good though

Comment (scarf005) [reply data/mods/rpg_system/main.lua:1071]: ~~imma lazy so let's go with current oneline approach~~
