### PR TITLE
fix(UI): shroud weaver location revealed by looking up a Z-level

### LINKED ISSUE #7882: Shroud Weavers' Darkness Cloak doesn't go across Z-levels
### Describe the bug

The shroud weaver's darkness cloak is supposed to hide its position, but if you press the "Look around" key and look up one Z-level, its position gets revealed.

### Steps To Reproduce

1. Find a shroud weaver
2. Press "x" or whatever your look around key is
3. Press "Page Up" to look up a Z-level
4. You can now see the shroud weaver on the Z-level below

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 11 (25H2)
- Game Version: v0.9.1 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language:  English
- Mods loaded: 
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    UDP Redux [udp_redux],
    Pride Flags for BN [pride_flags],
    Tablet e-book [tablet_ebook],
    Change Hairstyle [change_hairstyle]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change (The Why)

fixes #7882

## Describe the solution (The How)

- on looking around: update visibility cache based on player's z-level not camera's
- prevent underlying game UI from drawing during the loading popup
- force map cache rebuild on game load to prevent uninitialized lighting/visibility artifacts. (shroud weaver is shown for split second then disappears on load)

says GPT-5.2

### Before

Cataclysm: Bright Nights - 2f48be5fc5 (2026-01-14)_01
Cataclysm: Bright Nights - 2f48be5fc5 (2026-01-14)_02

### After

https://github.com/user-attachments/assets/8526b8ce-de86-43ae-93ca-bd76234b9a6d

## Additional context

average vibe coder be like: burn like 20 request and awake till 2:30am 

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -2743,9 +2743,13 @@ bool game::load( const save_t &name )
             std::bind( &game::unserialize, this, _1 ) ) ) {
         return false;
     }
-    // This needs to be here for some reason for quickload() to work
-    ui_manager::redraw();
-    refresh_display();
+    // This needs to be here for some reason for quickload() to work.
+    // Prevent underlying game UI from drawing while we're still in the loading popup.
+    {
```
Comment (chaosvolt) [inline src/game.cpp:2748]: This is just bracketed for no clear reason and no if statement? Does that even do anything?

Comment (scarf005) [reply src/game.cpp:2748]: code organization. if you insist...

Comment (scarf005) [reply src/game.cpp:2748]: rebased and force-pushed on 2a49efbcf128fc194ecf90f548331c333d21b21a

Comment (chaosvolt) [reply src/game.cpp:2748]: I just wanted to be sure it doesn't break anything since didn't know if there was a point to it. If it runs it anyway without issue then it's fine then.
